### ISSUE TITLE
Tender: Review PD coursework with grammar tool

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Tenders#3]
https://docs.google.com/document/d/1q8KC5L9tU5YgAxuM7lwj74AjCGQv1HXP0Lz-kYz9VWM/edit?usp=sharing

Submit your bids by commenting on this issue. You can see a template bid here https://docs.google.com/document/d/1_ZYRPX4JnDdY1F_C1CVyq99YPuV33eDs1Lk5A0wOBOE/edit#heading=h.tqtjzcfetl58

Finance informs that the winning contractor must have or purchase Professional Indemnity Insurance. Please itemise the cost on your bid and we will pay this before signing the contract.

We will leave this tender open until 

_DECEMBER 19 2023 23:00 UTC_ 
EXTENSION: JANUARY 1 2024 23:00 UTC 

and then give our decision by 

_DECEMBER 22 2023 15:00 UTC_
EXTENSION: JANUARY 8 2024 23:00 UTC

**Comment by haroon-ali-dev** [comment]
Hi Karen. Can't access the first doc, says access needed.

**Comment by kfklein15** [comment]
Updated it.

**Comment by Doris-Siu** [comment]
Hi Karen, may I ask what/how's the current CYF infrastructure or where I could learn more about that? Thanks.

**Comment by haroon-ali-dev** [comment]
@kfklein15 How are trainees currently submitting PD coursework? Are they still using Google Classroom? 
In the doc it says:

"Submission process flexibility: We are happy to consider solutions that require trainees to paste their work as a comment on their coursework issue or open it as a pull request to their coursework planner."

Do they now submit on GitHub? Could you explain the current process please?
Thanks.

**Comment by kfklein15** [comment]
1. Currently, they are using GitHub Projects with a repo for each module. This is the [HTML-CSS example](https://github.com/CodeYourFuture/Module-HTML-CSS/issues?q=is%3Aissue+is%3Aopen+pd). 
2. They fork the repos for every module and add them to a board in which they manage their coursework. Example of the forks view of [this repository](https://github.com/CodeYourFuture/Module-HTML-CSS/forks).
3. [Example of a coursework planne](https://github.com/PERicci?tab=projects)r of one of our trainees.
4. The Coursework issue is identified as PD on the title. The description explains what is expected to be done. Replies are give on as comments or attaching files (we don't have yet a standard, which is where your ideas come in)
5. Coursework is reviewed by volunteers and feedback given as a comment on the issue.

Let me now if this clarifies it all.

**Comment by haroon-ali-dev** [comment]
Everything is perfectly clear now. Thank you 😄.

**Comment by haroon-ali-dev** [comment]
# Qualified Supplier

## Declaration
I am a qualified supplier, and I am tendering for this work.
- I am a CYF-certified developer.
- I have a minimum of 4 kyu on my [Codewars profile](https://www.codewars.com/users/haroon-ali-dev) and I am happy to walk through any kata on my profile on request.
- I have a portfolio website with at least two team and two solo projects. I have provided links.
- I have right to work in the UK which I can prove with an online share code.

## Portfolio
- [Portfolio website](https://haroon-ali-portfolio.vercel.app/)
- [Solo project 1](https://github.com/haroon-ali-dev/point-of-sale)
- [Solo project 2](https://github.com/haroon-ali-dev/google-maps-crm)
- [Team project 1](https://github.com/Miladepour/SyntaxSquad-Project-Kunji)
- [Team project 2](https://github.com/haroon-ali-dev/event-manager)

## Contact Details
- Name: Haroon Ali
- Email: haroon.ali.1104@gmail.com
- CV: [View](https://docs.google.com/document/d/1RdoTHMU6o7SDpyD36igBgygytLlTbbKw6sYC-uO1UmE/edit?usp=sharing)

# Proposal
CodeYourFuture faces a critical challenge in ensuring the quality of coursework submissions by trainees, specifically in terms of grammar accuracy. The current manual review process is time-consuming and prone to human error, impacting the efficiency of the learning environment. To address this issue, I propose the development of a robust solution that automates the grammar checking process seamlessly within the GitHub platform.

This solution involves the creation of a dedicated GitHub app that functions as a serverless application. This app, hosted on AWS in a Docker container alongside a self-hosted LanguageTool instance, will integrate seamlessly with trainees' GitHub repositories. Trainees will submit their coursework as issue comments, webhooks will be sent to the app where it will initiate an automatic grammar check by communicating with the LanguageTool instance and send the feedback to the trainees.

## Components

### 1. GitHub App
- A serverless application hosted on AWS within a Docker container.
- Utilizes GitHub webhooks to receive coursework submissions as issue comments from trainees.
- Manages the communication flow between the GitHub repository and the LanguageTool instance.

### 2. LanguageTool Instance
- Self-hosted grammar checking tool running within the Docker container.
- Thoroughly checks the submitted coursework for grammar errors and provides detailed feedback.
- Communicates the results back to the GitHub app for further processing.

### 3. Workflow
- Trainees paste their coursework text into an issue comment on their GitHub repositories.
- The GitHub app, triggered by webhooks, sends the coursework text to the LanguageTool instance for grammar checking.
- The LanguageTool instance thoroughly analyzes the text and sends the results back to the GitHub app.
- The GitHub app posts an issue comment with detailed information about the grammar errors, if any.
- Trainees make corrections and re-submit until the GitHub app responds with a message saying that there are no grammar mistakes.

## Benefits
### 1. Efficiency
- Streamlines the coursework submission process by automating grammar checks, reducing manual effort.
- Enables trainees to receive immediate feedback, enhancing the learning process.
### 2. Accuracy
- Ensures a thorough and consistent evaluation of grammar in coursework submissions.
- Minimizes the risk of overlooking errors, enhancing the overall quality of trainee work.
### 3. User-Friendly
- Seamless integration into the GitHub platform with easy installation links for trainees to set up the GitHub app on their forked repositories.
- Simplifies the feedback loop, allowing trainees to iteratively improve their coursework until achieving error-free submissions.

By implementing this solution, I aim to significantly enhance the efficiency and quality of the coursework review process for CodeYourFuture, empowering trainees to excel in their learning journey.

# Deliverables
- Identify a suitable format for coursework submission - £50 - `20th January 2024`
- GitHub app and LanguageTool Docker instance - £250 - `1st March 2024`
    - Includes `Automated check on submission`.
    - Includes `Automated feedback`.
- Deployment of GitHub app on Netlify and LanguageTool Docker instance on AWS - £100 - `1st April 2024`
- Transition plan - £50 - `2nd April 2024`
- Six month bonus - £100 - `1st October 2024`

# Considerations
- It is maybe possible to have the coursework submission format as PDFs. The trainees export the Google Doc as a PDF, upload to the issue comment which will turn it into a link and then maybe the GitHub app can use that link with a JavaScript library to extract the text from the PDF.
- I have chosen LanguageTool over Grammarly because Grammarly does not have an API for grammar checking. All they had were some SDKs for developers to integrate with HTML code which are being discontinued. Have a look at https://developer.grammarly.com/sdk-deprecation.
-  I have chosen the self-hosted LanguageTool instance because all the grammar checking APIs I've researched seem to offer basic checking with basic plans and all plans seem to be paid plans. They all also have limits such as rate limits, maximum amount of text etc. LanguageTool does offer a free API but it has only basic checking along with the aforementioned limits. With the self-hosted LanguageTool instance, CodeYourFuture will have full and unrestricted access to the best language checker on the market. **This will enable CodeYourFuture to provide the best automated language checking to the trainees, greatly enhancing the trainees' English language proficiency.**
- I have gone with the Docker solution for deployment because the open-source self-hosted LanguageTool instance comes with pre-made Docker images and it is much better/easier to deploy the GitHub app as a serverless function in the same container or a separate container on AWS rather than doing two separate deployments to two separate platforms such as Netlify and AWS.

# Further Details
- Grammar, spelling and punctuation are all checked.
- It can output a count of total mistakes.
- It will show examples for the basic checking only as it does not have premium features.
- It will show all spelling mistakes with suggestions.
- It shows errors as well as suggestions.
- The input file can be anything for which a Node.js text-extracting package is available.

**Comment by kfklein15** [comment]
@Doris-Siu , did you see the details I added to it? Let us know if you have more questions.

**Comment by kfklein15** [comment]
Amended the description with the extension dates.

**Comment by kfklein15** [comment]
Amended the delivery date.

**Comment by leilafaez** [comment]
Hello @kfklein15,

I have a few questions regarding this project and the Supplier Declaration part

1. Could you please provide more details about having/obtaining Professional Indemnity Insurance?
2. Is it necessary for the language-checking tool to cover all languages? (This question is based on scalability.)
3. Do we only need to perform checks on issues labeled as "PD"?

Thank you

**Comment by kfklein15** [comment]
@leilafaez :
1. You can go to Professional Indemnity Insurance comparison sites (same as you would for any other insurance). For example: [MoneySuperMarket](https://www.moneysupermarket.com/business-insurance/professional-indemnity/)
2. No, only English, since all our courses and coursework are in English.
3. Yes, only the PD issues would be checked.
Thank you.

**Comment by leilafaez** [comment]
### Declaration

- I am a CYF-certified developer.
- I have 5 kyu on my [Codewars profile](https://www.codewars.com/users/Leilafa) and I am happy to walk through any kata on my profile on request.
- I have a [portfolio](https://leilafaez-portfolio.vercel.app/) website with [one team](https://animalcharityevaluators.org/for-charities/voting-methods-for-group-decisions/#/) and [one solo](https://content-management-app-pi.vercel.app/) project. 
- I have the right to work in the UK which I can prove with an online share code.

### Contact details
Name: Leila Faez
Email: leila.faez@gmail.com
CV : [Review](https://leilafaez-portfolio.vercel.app/cv)

### Proposal
**Project Proposal for Automated Grammar and Language Checker Integration**

**_Introduction_**
This proposal outlines a solution for integrating an automatic grammar and language checking system into the current coursework submission and review process managed on GitHub Projects. This solution aims to enhance writing proficiency within coursework submissions by automatically identifying and reporting English language errors. This will significantly reduce the time volunteers spend on grammar correction and allow them to focus on providing higher-value feedback.

**_Problem Statement_**
The current review process for coursework submissions managed as issues within GitHub Projects, is manual and time-intensive. Volunteers review written content for grammatical accuracy, which is essential for the professional development of trainees. However, this manual process needs to improve scale and efficiency.

**_Proposed Solution_** 
The proposed solution entails the deployment of a self-hosted automated language checking system within GitHub Issues coordinated by GitHub Actions. Through diligent R&D, a suitable language-checking tool will be selected to provide extensive grammar checks for submissions tagged with “PD”.

**Components**

1. Setting Up the Infrastructure:

  - Secure AWS server provision.
  - Installation and configuration of the chosen language checking system.
  - Customization of the system with tailored rules and checks

2. GitHub Actions Configuration:

  - Development of a GitHub Action specific to the project repository.
  - Trigger setup for the Action on the creation and editing of “PD” tagged issues.
  - Workflow formulation for text extraction from the issue for analysis.

3. Workflow outline

  - **Submission & Activation**: Coursework is posted within GitHub issues, initiating the automated Action.
  - **Content Evaluation**: The GitHub Action transmits text to the language checking server for analysis.
  - **Results Communication**: Identified linguistic issues are conveyed back via a comment in the GitHub issue.
  - **Progressive Refinement**: Revisions are made by trainees, and the cycle repeats until grammatical validation is achieved

  
**_Benefit_**

  - **Data Privacy:** No data is sent to external services; all checks are done within the security perimeter of the self-hosted environment.
  - **Scalability:** The self-hosted option can scale without additional incremental costs, accommodating the growth of the CodeYourFuture project
  - **Cost-Effectiveness:** After the initial setup, the ongoing costs are predictable and controlled; there are no per-check or surcharges based on usage.
  - **Efficiency:**
        - Saves time for trainees and volunteers by automating the proofreading process.
        - Reduces the manual effort of identifying and correcting language mistakes.

### Implementation Timeline
**The project will be started on the 1st of February.**

- R&D for Tool Selection: `7 February`
- Language Checking System Server Setup: ` 22 March`
- GitHub Actions Development and Testing: `7 May`
- Deployment and Operational Launch: `22 May`

### Deliverables

- Research and Development: Complimentary analysis and selection of the optimal automated language checking tool provided as a value-added service to ensure the project’s success.
- System Infrastructure: A fully functional self-hosted language checking instance. `£100`
- Deployment Configuration (AWS): Server setup to host the tool. ` £200`
- Initial GitHub Action: Development of Action linked to the language checking server. `£100`
- GitHub Action Improvement: Enhancement of the Action for optimal operation. `£50`
- Support and Maintenance: Six-month post-deployment support. `£50`

### Considerations

1. Actions are ideal for an event-driven approach where grammar checks are needed at specific points in the development flow (like on PR creation or when an issue is posted or updated). So Using a GitHub Action would be suitable to quickly integrate grammar checks into our workflow without needing to set up a separate server or web service.
2. Licensing: Any chosen language checking system will be utilized in full compliance with its licensing terms, ensuring legal and ethical use within our project’s scope.

**Comment by BoshraM** [comment]
We are qualified suppliers, and we are tendering for this work.
**Qualified Supplier Declaration**
I am a  CYF-certified developers
I have a minimum of 4kyu on Codewars, and I am happy to walk through any kata on my profile on request.
I maintain my own [portfolio](https://taupe-scone-2cb855.netlify.app/) website with at least one team and two solo projects, and I have provided the link in my portfolio.
I  have read and agreed to the definition of done

**Contact details**
 
Name: Boshra Mahmoudi
Email: [gbboshra@gmail.com](mailto:gbboshra@gmail.com)
CV: [Boshra 'CV](https://docs.google.com/document/d/19fgG0V60k1R2dJR69RgWQkQawbs04DsSmGX2vDbMYTI/edit)

**Qualified Supplier Declaration**
I am a  CYF-certified developers
I have a minimum of 4kyu on Codewars, and I am happy to walk through any kata on my profile on request.
I maintain my own [portfolio](http://p1-3q8u.onrender.com/) website with at least one team and two solo projects, and I have provided the link.
I  have read and agreed to the definition of done

**Contact details**

Name: Bahare Bahreinian
Email:[ itxbb09@gmail.com](mailto:itxbb09@gmail.com)
CV: [Bahare 'CV](https://drive.google.com/file/d/1PCg8vXm7t_G7SEnoldipMVtp0A5Qdc0-/view?usp=sharing)

**Proposal**

**Problem assessment**
The main issue we're tackling with this idea is that many trainees need help improving their writing skills to meet the standards expected in professional settings. Even though there are helpful tools like Grammarly available, a lot of trainees forget to use them. This oversight affects the quality of their work. To solve this problem, we want to simplify things by setting up an automatic system using Grammarly within GitHub. This way, we can create a smooth and consistent process to help trainees improve their writing skills.

**Trainee Submission**
Trainees can submit their coursework by creating a comment on an issue with a title starting with [PD].

**Workflow Steps:**
1- Grammar Check: If the pull request title starts with [PD], the Grammar Check workflow will run a Node.js script that checks for grammar and spelling mistakes in the coursework.

2- Provide Feedback: Based on the grammar check results, feedback will be provided as comments on the issue. If the coursework is error-free, the system will proceed to the next step.

3- Update Coursework Status: If there are no grammar or spelling mistakes, the GitHub API will be used to update the coursework status. The issue can be labelled or commented on, indicating that the coursework is done and ready for volunteer review.

**Deliverables**
£60 Identify a suitable format for coursework submission: 25th January 2024
£120 Automated check on submission: 25th February 2024
£70 Automated feedback:(Including a list of errors, or if the text is error-free, updating the status of the issue to "done.") :10th March 2024 
£70 Deployment of the system into CYF infrastructure: 25th March 2024
£50 Transition plan: 15th April 2024
£50 Six-month bonus: 15th October

**Consideration**
We're exploring both free and paid APIs to optimise our approach. While the effectiveness of free options is uncertain, we prioritise considering a paid API for enhanced results. Our goal is to find an efficient solution to elevate coursework quality.

**Comment by Barny-6** [comment]
### 🤝 Contract Awarded
Well done to all of you for submitting a bid. They were strong contenders, and after considering the applications, we have decided to award this contract to [@haroon-ali-dev](https://github.com/haroon-ali-dev) pending these amendments: 

- Grammar AND spelling AND punctuation should be checked
- On the point “The GitHub app posts an issue comment with detailed information about the grammar errors, if any”, it should include a count of total grammar and spelling errors. Will it show all the examples? If someone has 100 mis-spellings, will it show all?
- Will only actual errors be highlighted, or will it also have changes such as “could be clearer” or “could be more concise”?
- PDF: why can’t it be a Word document?
- Please break down your deliverable cost per deliverables on the original bid + any other added
GitHub app and LanguageTool instance inside Docker containers - £300 - 15th February 2024
? Identify a suitable format for coursework submission so that grammar checks run automatically
? Automated check on submission: when a trainee submits their coursework, an automated Grammarly check is run
? Automated feedback: list errors or a success message for correct work

We'll revisit pricing once you've broken down the deliverable cost in your original bid.

### 👣 Next steps
Book a call with [@kfklein15](https://github.com/kfklein15), link in her Slack Profile
🎉 Thank you.

### 🎚️ Feedback
If your bid was unsuccessful and you would like private feedback, please write to @barny@codeyourfuture.io, and I will send it to you directly. Please include a link to your bid. And if you would like to help our community learn, please post that feedback in this thread!

**Comment by kfklein15** [comment]
Thanks, @haroon-ali-dev , all the answers have been given on your original proposal in "Further details" and you updated the detailed costs. It is all ok and clarified and I am approving this.
FYI @Barny-6

**Comment by kfklein15** [comment]
Example done: https://github.com/haroon-ali-dev/github-app-testing/issues/1
Repo: https://github.com/CodeYourFuture/pd-grammar-bot

**Comment by kfklein15** [comment]
We are talking to Language Tool to see if we can get free access to their API. However, they will reply to us next week, when I am on holiday. These delays may cause an overall delay in the delivery of the project since the deployment cannot be worked on until we have this final decision.
We will try to reduce to remediate this as much as we can.
FYI @haroon-ali-dev

**Comment by haroon-ali-dev** [comment]
@kfklein15 

These are the categories of mistakes that the basic version of LanguageTool detects:
- Capitalization
- Collocations
- Commonly Confused Words
- Grammar
- Nonstandard Phrases
- Possible Typo
- Punctuation
- Redundant Phrases
- Style
- Semantics
- Typography
- Upper/Lowercase
- Miscellaneous

[This is where all categories with examples can be found.](https://community.languagetool.org/rule/list?lang=en)
